version: '2.0'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    links:
    - postgres
    environment:
      DJANGO_SETTINGS_MODULE: docker.settings
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shield
